/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us/index'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as TradingIndexRouteImport } from './routes/trading/index'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingIndexRoute = TradingIndexRouteImport.update({
  id: '/trading/',
  path: '/trading/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/trading/': typeof TradingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/trading': typeof TradingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/trading/': typeof TradingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about-us/' | '/platform/' | '/trading/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about-us' | '/platform' | '/trading'
  id: '__root__' | '/(home)/' | '/about-us/' | '/platform/' | '/trading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  TradingIndexRoute: typeof TradingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/': {
      id: '/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof TradingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  TradingIndexRoute: TradingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
